Description: >
  Calvin Karegyeya | Udacity IAC project 2023
  AWS-CloudFormation script to create a Bastion access to the Udagram server in the private subnets.

Parameters:
  EnvironmentName:
    Description: An environment name that will be prefixed to resource names
    Type: String
    Default: UdagramApp

  SourceIP:
    Description: Ip address to allow SSH access to the bastion host
    Type: String

  S3BucketKeyName:
    Description: S3 Bucket where ssh key is hosted
    Type: String

  ## You have to create a .pem file, and upload it to S3 bucket for KEY pairs.
  BastionSSHKey:
    Description: SSH Key to access bastion host
    Type: 'AWS::EC2::KeyPair::KeyName'
    Default: udagram-bastion

  UdagramSSHKey:
    Description: SSH Key to access udagram host
    Type: 'AWS::EC2::KeyPair::KeyName'
    Default: udagram

Mappings:
  WebAppRegion:
    us-west-2:
      HVM64: ami-0a588942e90cfecc9

Resources:
  BastionIamRole:
    Type: AWS::IAM::Role
    Properties:
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/AmazonS3FullAccess'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: 'Allow'
            Principal:
              Service:
                - 'ec2.amazonaws.com'
            Action:
              - 'sts:AssumeRole'
      Path: '/'

  BastionIamInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: '/'
      Roles:
        - !Ref BastionIamRole

  BastionSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: SG to access to bastion host
      VpcId:
        Fn::ImportValue: !Sub '${EnvironmentName}-VPCID'
      SecurityGroupEgress:
        - IpProtocol: '-1'
          CidrIp: 0.0.0.0/0
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '22'
          ToPort: '22'
          CidrIp: !Sub ${SourceIP}

  Bastion1:
    Type: AWS::EC2::Instance
    DependsOn:
      - BastionSecurityGroup
      - BastionIamInstanceProfile
    Properties:
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          apt-get update -y
          apt-get install unzip awscli -y
          cd /home/ubuntu
          aws s3 cp s3://${S3BucketKeyName}/${UdagramSSHKey}.pem /home/ubuntu
          chmod 400 ${UdagramSSHKey}.pem
      IamInstanceProfile: !Ref BastionIamInstanceProfile
      SecurityGroupIds:
        - Ref: BastionSecurityGroup
      SubnetId:
        Fn::ImportValue: !Sub '${EnvironmentName}-PUB1-SN'
      ImageId: !FindInMap [WebAppRegion, !Ref 'AWS::Region', HVM64]
      InstanceType: t3.small
      KeyName: !Sub ${BastionSSHKey}

  EIP1:
    Type: AWS::EC2::EIP
    Properties:
      Domain:
        Fn::ImportValue: !Sub '${EnvironmentName}-VPCID'

  EIPAssociation1:
    Type: AWS::EC2::EIPAssociation
    DependsOn:
      - Bastion1
      - EIP1
    Properties:
      InstanceId:
        Ref: Bastion1
      AllocationId:
        Fn::GetAtt:
          - EIP1
          - AllocationId

  Bastion2:
    Type: AWS::EC2::Instance
    DependsOn:
      - BastionSecurityGroup
      - BastionIamInstanceProfile
    Properties:
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          apt-get update -y
          apt-get install unzip awscli -y
          cd /home/ubuntu
          aws s3 cp s3://${S3BucketKeyName}/${UdagramSSHKey}.pem /home/ubuntu
          chmod 400 ${UdagramSSHKey}.pem
      IamInstanceProfile: !Ref BastionIamInstanceProfile
      ImageId: !FindInMap [WebAppRegion, !Ref 'AWS::Region', HVM64]
      InstanceType: t3.small
      KeyName: !Sub ${BastionSSHKey}
      SecurityGroupIds:
        - Ref: BastionSecurityGroup
      SubnetId:
        Fn::ImportValue: !Sub '${EnvironmentName}-PUB2-SN'

  EIP2:
    Type: AWS::EC2::EIP
    Properties:
      Domain:
        Fn::ImportValue: !Sub '${EnvironmentName}-VPCID'

  EIPAssociation2:
    Type: AWS::EC2::EIPAssociation
    DependsOn:
      - Bastion2
      - EIP2
    Properties:
      InstanceId:
        Ref: Bastion2
      AllocationId:
        Fn::GetAtt:
          - EIP2
          - AllocationId


Outputs:
  CIDRBastion1:
    Description: The CIDR of Bastion Host 1
    Value: !Join ['', [!GetAtt Bastion1.PrivateIp, !Sub '/32']]
    Export:
      Name: !Sub ${EnvironmentName}-BASTION1-CIDR

  CIDRBastion2:
    Description: The CIDR to the Bastion Host 2
    Value: !Join ['', [!GetAtt Bastion2.PrivateIp, !Sub '/32']]
    Export:
      Name: !Sub ${EnvironmentName}-BASTION2-CIDR

